### ISSUE TITLE
I there any way that we perhaps can chage the speed output (KM/h) to pace (minutes/KM)?

### ISSUE THREAD

**Issue by ajid77** [oldnapalm/vspeed#1]
I think a wide range of paces is better as compare to KM/h speed. as the range, eg 100-120bpm = 7KM/h. the range is to wide

**Comment by oldnapalm** [comment]
The speed output is in m/s as specified in the Stride Based Speed and Distance ANT+ Device Profile (https://www.thisisant.com/resources/stride-based-speed-and-distance-monitor/), it's a function of the app receiving the data to display it in the preferred user unit.

![2023-02-20 07_16_29-ANT+_Device_Profile_-_Stride_Based_Speed__Distance_Rev_1 6 pdf - Perfil 1 — Micr](https://user-images.githubusercontent.com/38410858/220078109-92f7c46d-c4ea-427a-9e32-ce9809f9ee41.png)

Regarding the ranges in zones.csv, it's just an example, you can add lines as you want with any interval between them (notice that the intermediate values will be interpolated so you don't need to use a very short interval).
