### ISSUE TITLE
suggestion : Cycling Cadence Sensor as Running Pod.

### ISSUE THREAD

**Issue by ajid77** [oldnapalm/vspeed#2]
I believe that Running Pod (that read cadence and pace) is too expensive, but accurate especially the ANT+ version.
And I somehow believe the "Cycling Cadence Sensor" acts almost the same, (provide cadence but not speed for cycling, This has made me wonder if vSpeed can somehow act as "virtual pace for running" using the cadence from the Cycling sensor. would be brilliant and helps promoting Cyclist to do running in virtual apps such as Zwift and GTBikeV.

If is can be done and possible, here are the data conversion table i would suggest to be use:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ajid77/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ajid77/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Cadence (RPM) | Speed (Km/h)
5 | 0
165 | 9
170 | 10
175 | 11
180 | 12
185 | 13
190 | 14
200 | 15

**Comment by oldnapalm** [comment]
Pushed a test version, please try. I don't have a cadence sensor anymore, can't test it.

If you need a Windows executable, download from https://github.com/oldnapalm/vspeed/actions

**Comment by ajid77** [comment]
I've tried the test version and it seem to work. It' just that the converted cycling-cadence doesn't appear as "running pod cadence" for Zwift. but as for GT Bike V, It does appear, but the cadence reading is only for one-feet. mean. if it 160SPM, it will be 80SPM.

I notice the nature of this cycling-cadence sensor if; it only read 1RPM for a 1 complete cycle. mean, there will be on and off for each reading. as we know that running cadence only at 1/4 complete cycle  (i guess)

I don't think there's a problem with the application. It works i can say.

and I'm using this table

Cadence (SPM)	Speed (km/h)
65	3
70	4
75	5
80	6
85	7
90	8
95	9
100	10
105	11
110	12

**Comment by oldnapalm** [comment]
Try if this makes any difference regarding cadence display on Zwift https://github.com/oldnapalm/vspeed/actions/runs/6504351889

**Comment by ajid77** [comment]
tested with below table setting. It's works better.
some thing that i notice.

with GTBikeV 7.2.0 : it works. just need to run exe file first before game. and don't make a move before the GTBikeV script started, or it will never end running. LOL
Pace, Cadence, HR perfectly shown.

Below are the table I'm using:
......................................................................................................................................................
Cadence (SPM)	Speed (km/h)
60	0
65	5
70	6
75	7
80	8
85	9
90	10
95	11
100	12
105	13
110	14
115	15

.................................................................................................................................................................
with GTBikeV 7.3.0 = I couldn't run it, 

with Zoffline : I coundn't get it run. the exe is running, but zoffline is connected (speed and cadence), but no date is received in zoffline.


and one more thing to include, is there is different in pace showing: the exe is 7KM/H and will never ever stop even after running. while as in GTBikeV is will show 11KM/H tho the exe shown 7KM/H.

here is the sample fit file https://www.strava.com/activities/10030041518

**Comment by oldnapalm** [comment]
These problems started with the second version or happened also with the first?

Try if the runner stops with this version and if you run the exe before the game.

https://github.com/oldnapalm/vspeed/actions/runs/6508784742

I think GTBikeV shows the cadence because it's reading the cycling cadence directly. For Zwift it would be necessary to send it in the SDM but it would need many tests so I won't try to do it for now, will wait when I have a cadence sensor in hands.

**Comment by oldnapalm** [comment]
Disregard the last link, try this one https://github.com/oldnapalm/vspeed/actions/runs/6509092411

**Comment by ajid77** [comment]
Allrite. It works now. starts and stop accordingly to my movement. tested in GT Bike V.

**Comment by oldnapalm** [comment]
How about Zwift, it never worked or only stopped working in the second version?

**Comment by ajid77** [comment]
As for the zwift.

The first exe version;
Speed sensor connected
Cadence sensor never connected

The avatar did run as I move my leg. 

The 2nd exe version;
Speed sensor  connected. But avatar never moved, tho I'm physical moving

**Comment by oldnapalm** [comment]
Does this last version work with Zwift (speed)?

**Comment by ajid77** [comment]
Sorry, forget to mention. It works. Better this time

Start n stop works now.
No issue with connection.

**Comment by oldnapalm** [comment]
> while as in GTBikeV is will show 11KM/H tho the exe shown 7KM/H.

Is speed matching now?

A final test for cadence on Zwift, if it doesn't work now I will wait until I have a sensor to test

https://github.com/oldnapalm/vspeed/actions/runs/6510596063

**Comment by oldnapalm** [comment]
Disregard the last link, try this one https://github.com/oldnapalm/vspeed/actions/runs/6510703334

**Comment by ajid77** [comment]
> Disregard the last link, try this one https://github.com/oldnapalm/vspeed/actions/runs/6510703334

The speed in zwift and exe is matched. cool
![image](https://github.com/oldnapalm/vspeed/assets/31261806/62932ea4-a264-47ec-a617-eed209ee4a68)

Up to this point. I think it really been a progress. tq once again,
if anything do let me know. I can do testing if needed.
good nite mate

**Comment by oldnapalm** [comment]
But still no cadence on Zwift apparently, so I reverted the last changes.

If you can do a final test I will merge this for now

https://github.com/oldnapalm/vspeed/actions/runs/6511225747

**Comment by oldnapalm** [comment]
Another try for cadence on Zwift https://github.com/oldnapalm/vspeed/actions/runs/6513889347

If this doesn't work then just confirm if the previous one is fine (disregarding Zwift cadence).

**Comment by ajid77** [comment]
> But still no cadence on Zwift apparently, so I reverted the last changes.
> If you can do a final test I will merge this for now
> 
> https://github.com/oldnapalm/vspeed/actions/runs/6511225747

STILL no cadence data appear  for this exe version in zwift. 
Everything else are okey with this version
![image](https://github.com/oldnapalm/vspeed/assets/31261806/726c8f8b-33b4-4d90-8eb6-27e61f90c834)

**Comment by ajid77** [comment]
> Another try for cadence on Zwift https://github.com/oldnapalm/vspeed/actions/runs/6513889347
> 
> If this doesn't work then just confirm if the previous one is fine (disregarding Zwift cadence).

The speed data doesn't appear, totally
But, surprisingly the cadence data has appear but only for one or two second before gone to zero.  
![image](https://github.com/oldnapalm/vspeed/assets/31261806/cbce53cf-9ef7-43c3-80fb-2e66b58600a7)

**Comment by oldnapalm** [comment]
Another test https://github.com/oldnapalm/vspeed/actions/runs/6514264695

**Comment by oldnapalm** [comment]
Disregard the last one, I made a mistake.

Try this https://github.com/oldnapalm/vspeed/actions/runs/6514368736

**Comment by ajid77** [comment]
> Disregard the last one, I made a mistake.
> 
> Try this https://github.com/oldnapalm/vspeed/actions/runs/6514368736

I've got this error for this final exe version
![image](https://github.com/oldnapalm/vspeed/assets/31261806/5ad6b696-f81c-47eb-a004-2aa7171dfe85)

**Comment by oldnapalm** [comment]
Another mistake.

Try this one https://github.com/oldnapalm/vspeed/actions/runs/6514731959

**Comment by ajid77** [comment]
> Another test https://github.com/oldnapalm/vspeed/actions/runs/6514264695

same error came out here. it says

Starting ANT node
Starting cadence sensor
Starting SDM with ANT+ ID 24513
Main wait loop
cannot access local variable 'speedUpdated' where it is not associated with a value
cannot access local variable 'speedUpdated' where it is not associated with a value
cannot access local variable 'speedUpdated' where it is not associated with a value
cannot access local variable 'speedUpdated' where it is not associated with a value
cannot access local variable 'speedUpdated' where it is not associated with a value
cannot access local variable 'speedUpdated' where it is not associated with a value
cannot access local variable 'speedUpdated' where it is not associated with a value

before self-terminated i assume:

cannot access local variable 'speedUpdated' where it is not associated with a value
Exception in thread Thread-1 (EventPump):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "ant\core\event.py", line 50, in EventPump
  File "ant\core\driver.py", line 79, in read
  File "ant\core\driver.py", line 244, in _read
  File "usb\core.py", line 423, in read
  File "usb\core.py", line 1029, in read
  File "usb\backend\libusb0.py", line 553, in bulk_read
  File "usb\backend\libusb0.py", line 692, in __read
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] reaping request failed, win error: A device attached to the system is not functioning.\r\n\n'

**Comment by ajid77** [comment]
> Another mistake.
> 
> Try this one https://github.com/oldnapalm/vspeed/actions/runs/6514731959

Brilliant. Cadence data are now online.
![image](https://github.com/oldnapalm/vspeed/assets/31261806/120ae555-aa35-4ffd-8a49-e80426856f24)

But, just a slight note to be taken. the pace data are kinda constant until it reach the next cadence threshold which i stated in csv file.

**Comment by oldnapalm** [comment]
> But, just a slight note to be taken. the pace data are kinda constant until it reach the next cadence threshold which i stated in csv file.

Really? It doesn't make sense because the value sent is the one read from the sensor.

How does it behave in GTBike?

This version will double the cadence so you can check which sensor it's reading

https://github.com/oldnapalm/vspeed/actions/runs/6514826980

**Comment by ajid77** [comment]
> > But, just a slight note to be taken. the pace data are kinda constant until it reach the next cadence threshold which i stated in csv file.
> 
> Really? It doesn't make sense because the value sent is the one read from the sensor.
> 
> How does it behave in GTBike?
> 
> This version will double the cadence so you can check which sensor it's reading
> 
> https://github.com/oldnapalm/vspeed/actions/runs/6514826980

Yup! the cadence value in zwift has been double (the standard nature in zwift i notice). great to see it

regarding the pace data, what i mean is, the speed value only increase in absolute value which 7KM/h, 8KM/h, 9KM/h. which the vspeed HR version final, I notice the pace value can be 7.1KM/h, 8.5KM/h etc. which I'm not mistaken. more realistic i suppose

![image](https://github.com/oldnapalm/vspeed/assets/31261806/461e0afd-b770-49dd-b90f-87eba5ba240f)

where in #GTBikeV ; the cadence is display like always. in single leg value (not double in zwift). BUT, the pace keep on DISCONNECTING, on and off. never happens before


https://github.com/oldnapalm/vspeed/assets/31261806/cb85638a-8a47-4c5b-85d5-0492ee04e366

**Comment by oldnapalm** [comment]
Another test https://github.com/oldnapalm/vspeed/actions/runs/6515128421

**Comment by ajid77** [comment]
> Another test https://github.com/oldnapalm/vspeed/actions/runs/6515128421

on Zwift is good (Pace proportionate to cadence) 

https://github.com/oldnapalm/vspeed/assets/31261806/839c50d6-26db-45d5-ba09-b54beef7a9fe

while in GTBikeV:

abit crazy a the start before stable. quite a few time it read single leg cadence.

https://github.com/oldnapalm/vspeed/assets/31261806/952cb076-4a6d-4568-b31c-780047436a72


https://github.com/oldnapalm/vspeed/assets/31261806/408e8217-85cf-4c51-bfcf-bf19f94fb6f1

**Comment by oldnapalm** [comment]
Apparently Zwift doesn't like to receive the cadence every time, while GTBike wants it.

Test if this works better in GTBike (although it can cause problems in Zwift) https://github.com/oldnapalm/vspeed/actions/runs/6515379724

**Comment by ajid77** [comment]
GTBike wen't loko abit. too sensitive perhaps?

https://github.com/oldnapalm/vspeed/assets/31261806/84f40f04-2653-41f6-ac2f-2a7c4f978524

as for Zwift, i think it went crazy too. You're not wrong. the pace reading all over the places



https://github.com/oldnapalm/vspeed/assets/31261806/fcfb016c-603b-4b26-b497-fc38e5fc6676

My suggestion, perhaps we should kept the cadence reading just for one leg, (ie 180spm / 2 = 90spm). It's a signature for Stryd Pod if i'm not mistaken. so, same format should goes to GTBike and Zwift as well

**Comment by oldnapalm** [comment]
It was my mistake, time to sleep.

Try this https://github.com/oldnapalm/vspeed/actions/runs/6515569552

Regarding cadence, we can keep as it comes from sensor, but that is not the problem.

**Comment by ajid77** [comment]
> It was my mistake, time to sleep.
> 
> Try this https://github.com/oldnapalm/vspeed/actions/runs/6515569552
> 
> Regarding cadence, we can keep as it comes from sensor, but that is not the problem.

Great things to know. the exe is getting better in GTBikeV and Zwift. :)
cadence reading appear nicely i think so.
almost accurate as it suppose to be. and responsive too
![image](https://github.com/oldnapalm/vspeed/assets/31261806/2fc108ed-ddd6-4f08-8d42-50fd41e6b01d)

![image](https://github.com/oldnapalm/vspeed/assets/31261806/1898016f-7af1-401b-8bce-083e7900584b)

another great think to be noted is the Pace and Cadence can be received to Garmin watch too. mean, it act as much like running pod. congrats to you

**Comment by oldnapalm** [comment]
That's great news!

I made a small tweak, you should see no difference, but test this version just to make sure it didn't break anything

https://github.com/oldnapalm/vspeed/actions/runs/6517455346

**Comment by ajid77** [comment]
> That's great news!
> 
> I made a small tweak, you should see no difference, but test this version just to make sure it didn't break anything
> 
> https://github.com/oldnapalm/vspeed/actions/runs/6517455346

All are okey.

Cadence reading is shown in half (one leg) in GTBikeV, and double in Zwift. where I think it is where it was suppose to be.

I think It quite better in Zwift IMHO. responsive

**Comment by oldnapalm** [comment]
That's odd because it's being sent doubled in this version.

Maybe GTBike is reading from the sensor directly. You can try setting CADDEVICEID=24513 in the ini.

**Comment by ajid77** [comment]
You're right. I did read the Cadence Double when I sat the sensor ID.

The data a  bit crazy in the beginning when I start running, but I get better and normal after a few seconds. GTBikeV seem OK now

**Comment by oldnapalm** [comment]
> The data a bit crazy in the beginning when I start running, but I get better and normal after a few seconds.

This may be due to your conversion table, try to remove the first line (60,0), it's not necessary because "0,0" is added by default and it may be causing the issue.

I merged this in the main branch, the exe is included in https://github.com/oldnapalm/vspeed/releases/tag/nightly-build

Feel free to reopen the issue if you find any problems.
