### ISSUE TITLE
Garmin device registered the for cadence double

### ISSUE THREAD

**Issue by ajid77** [oldnapalm/vspeed#3]
As I am monitoring the cadence.exe, it seem that it is perform well in Strava, but not for Garmin device's watched that can recognize cycling cadence as stride base pod = It read the running cadence double. ei 150spm will be 300spm

perhaps if this can be fixed. It would be so nice

**Comment by oldnapalm** [comment]
Maybe the value should be sent as it comes from the cycling sensor and is up to the receiving app to double it if desired.

> Cadence - Measure of strides accumulated in time.
> Stride Count - Accumulated strides. **This value is incremented once for every two footfalls.**

https://www.thisisant.com/resources/stride-based-speed-and-distance-monitor/

**Comment by oldnapalm** [comment]
@ajid77 any luck with https://github.com/oldnapalm/vspeed/commit/5465bf28128f391ee71caebc2486c1848d580d11 ?

The updated exe is included in https://github.com/oldnapalm/vspeed/releases/tag/nightly-build

**Comment by ajid77** [comment]
Sorry about the long silent. Been busy this while. Doesn't get the opportunity to test it. Will report it soon once I got back home
